export const placeholderData = {
  budget: [
    {
      envelopeID: 1,
      envelopeTitle: "Income",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 1,
          envelopeID: 1,
          transactionDescription: "Bryant",
          date: "2024-12-01",
          amount: 4231,
          repeating: false,
        },
        {
          transactionID: 2,
          envelopeID: 1,
          transactionDescription: "Takeda",
          date: "2024-12-01",
          amount: 7800,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 3,
      envelopeTitle: "Savings",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 3,
          envelopeID: 3,
          transactionDescription: "Home",
          date: "2024-12-01",
          amount: 500,
          repeating: false,
        },
        {
          transactionID: 4,
          envelopeID: 3,
          transactionDescription: "Car",
          date: "2024-12-01",
          amount: 392,
          repeating: false,
        },
        {
          transactionID: 5,
          envelopeID: 3,
          transactionDescription: "Dog",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 6,
          envelopeID: 3,
          transactionDescription: "Utilities",
          date: "2024-12-01",
          amount: 229,
          repeating: false,
        },
        {
          transactionID: 7,
          envelopeID: 3,
          transactionDescription: "Phone",
          date: "2024-12-01",
          amount: 58,
          repeating: false,
        },
        {
          transactionID: 8,
          envelopeID: 3,
          transactionDescription: "Travel",
          date: "2024-12-01",
          amount: 250,
          repeating: false,
        },
        {
          transactionID: 9,
          envelopeID: 3,
          transactionDescription: "Emergency",
          date: "2024-12-01",
          amount: 250,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 4,
      envelopeTitle: "Housing",
      envelopeDescription: "Mortgages and HOA",
      transactions: [
        {
          transactionID: 10,
          envelopeID: 4,
          transactionDescription: "Mortgage",
          date: "2024-12-01",
          amount: 918,
          repeating: false,
        },
        {
          transactionID: 11,
          envelopeID: 4,
          transactionDescription: "HOA",
          date: "2024-12-14",
          amount: 150,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 5,
      envelopeTitle: "Transportation",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 12,
          envelopeID: 5,
          transactionDescription: "Tesla Lease",
          date: "2024-12-01",
          amount: 515,
          repeating: false,
        },
        {
          transactionID: 13,
          envelopeID: 5,
          transactionDescription: "Honda Loan",
          date: "2024-12-13",
          amount: 305,
          repeating: false,
        },
        {
          transactionID: 14,
          envelopeID: 5,
          transactionDescription: "Gas",
          date: "2024-12-13",
          amount: 100,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 6,
      envelopeTitle: "Utilities",
      envelopeDescription:
        "Utilities that are billed monthly and are pretty regular (electric, phone, internet)",
      transactions: [
        {
          transactionID: 15,
          envelopeID: 6,
          transactionDescription: "Internet",
          date: "2024-12-01",
          amount: 82.77,
          repeating: false,
        },
        {
          transactionID: 16,
          envelopeID: 6,
          transactionDescription: "T-Mobile",
          date: "2024-12-01",
          amount: 39,
          repeating: false,
        },
        {
          transactionID: 17,
          envelopeID: 6,
          transactionDescription: "Electric",
          date: "2024-12-05",
          amount: 160,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 7,
      envelopeTitle: "Groceries and Home",
      envelopeDescription:
        "Include items purchased for the home from Amazon, etc.",
      transactions: [
        {
          transactionID: 18,
          envelopeID: 7,
          transactionDescription: "Grocery Stores",
          date: "2024-12-01",
          amount: 1200,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 8,
      envelopeTitle: "Health",
      envelopeDescription: "Gym, doctors, chiropractor",
      transactions: [
        {
          transactionID: 19,
          envelopeID: 8,
          transactionDescription: "Planet Fitness",
          date: "2024-12-17",
          amount: 10.64,
          repeating: false,
        },
        {
          transactionID: 20,
          envelopeID: 8,
          transactionDescription: "Chiropractor",
          date: "2024-12-01",
          amount: 40,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 11,
      envelopeTitle: "Streaming Services",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 21,
          envelopeID: 11,
          transactionDescription: "Youtube Premium",
          date: "2024-12-03",
          amount: 24.45,
          repeating: false,
        },
        {
          transactionID: 22,
          envelopeID: 11,
          transactionDescription: "Netflix",
          date: "2024-12-08",
          amount: 24.45,
          repeating: false,
        },
        {
          transactionID: 23,
          envelopeID: 11,
          transactionDescription: "Spotify - Kevin",
          date: "2024-12-28",
          amount: 12.75,
          repeating: false,
        },
      ],
    },
  ],
  checking: [
    {
      envelopeID: 13,
      envelopeTitle: "Income",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 24,
          envelopeID: 13,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 8904,
          repeating: true,
        },
        {
          transactionID: 25,
          envelopeID: 13,
          transactionDescription: "Bryant",
          date: "2024-12-01",
          amount: 4231.61,
          repeating: true,
        },
        {
          transactionID: 26,
          envelopeID: 13,
          transactionDescription: "Takeda",
          date: "2024-12-01",
          amount: 7707.82,
          repeating: true,
        },
      ],
    },
    {
      envelopeID: 15,
      envelopeTitle: "Savings",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 27,
          envelopeID: 3,
          transactionDescription: "Home",
          date: "2024-12-01",
          amount: 500,
          repeating: false,
        },
        {
          transactionID: 28,
          envelopeID: 3,
          transactionDescription: "Car",
          date: "2024-12-01",
          amount: 392,
          repeating: false,
        },
        {
          transactionID: 29,
          envelopeID: 3,
          transactionDescription: "Dog",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 30,
          envelopeID: 3,
          transactionDescription: "Utilities",
          date: "2024-12-01",
          amount: 229,
          repeating: false,
        },
        {
          transactionID: 31,
          envelopeID: 3,
          transactionDescription: "Phone",
          date: "2024-12-01",
          amount: 58,
          repeating: false,
        },
        {
          transactionID: 32,
          envelopeID: 3,
          transactionDescription: "Travel",
          date: "2024-12-01",
          amount: 250,
          repeating: false,
        },
        {
          transactionID: 33,
          envelopeID: 3,
          transactionDescription: "Emergency",
          date: "2024-12-01",
          amount: 250,
          repeating: false,
        },
        // {
        //   transactionID: 59,
        //   envelopeID: 3,
        //   transactionDescription: "test",
        //   date: "2025-01-01",
        //   amount: 250,
        //   repeating: false,
        // },
      ],
    },
    {
      envelopeID: 16,
      envelopeTitle: "Housing",
      envelopeDescription: "Mortgages and HOA",
      transactions: [
        {
          transactionID: 34,
          envelopeID: 16,
          transactionDescription: "Mortgage",
          date: "2024-12-01",
          amount: 918,
          repeating: false,
        },
        {
          transactionID: 35,
          envelopeID: 16,
          transactionDescription: "HOA",
          date: "2024-12-14",
          amount: 150,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 17,
      envelopeTitle: "Transportation",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 36,
          envelopeID: 17,
          transactionDescription: "Tesla Lease",
          date: "2024-12-05",
          amount: 515,
          repeating: true,
        },
        {
          transactionID: 37,
          envelopeID: 17,
          transactionDescription: "Honda Loan",
          date: "2024-12-08",
          amount: 305.79,
          repeating: true,
        },
        {
          transactionID: 38,
          envelopeID: 17,
          transactionDescription: "Gas",
          date: "2024-12-05",
          amount: 31.38,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 18,
      envelopeTitle: "Utilities",
      envelopeDescription:
        "Utilities that are billed monthly and are pretty regular (electric, phone, internet)",
      transactions: [
        {
          transactionID: 39,
          envelopeID: 18,
          transactionDescription: "Electric",
          date: "2024-12-05",
          amount: 133,
          repeating: true,
        },
        {
          transactionID: 40,
          envelopeID: 18,
          transactionDescription: "T-Mobile",
          date: "2024-12-01",
          amount: 39,
          repeating: true,
        },
        {
          transactionID: 41,
          envelopeID: 18,
          transactionDescription: "Internet",
          date: "2024-12-02",
          amount: 83,
          repeating: true,
        },
      ],
    },
    {
      envelopeID: 19,
      envelopeTitle: "Groceries and Home",
      envelopeDescription:
        "Include items purchased for the home from Amazon, etc.",
      transactions: [
        {
          transactionID: 42,
          envelopeID: 19,
          transactionDescription: "Aldi, Stop n Shop",
          date: "2024-12-01",
          amount: 190.11,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 20,
      envelopeTitle: "Health",
      envelopeDescription: "Gym, doctors, chiropractor",
      transactions: [
        {
          transactionID: 43,
          envelopeID: 20,
          transactionDescription: "Chiropractor",
          date: "2024-12-04",
          amount: 40,
          repeating: false,
        },
        {
          transactionID: 44,
          envelopeID: 20,
          transactionDescription: "Chiropractor",
          date: "2024-12-19",
          amount: 40,
          repeating: false,
        },
        {
          transactionID: 45,
          envelopeID: 20,
          transactionDescription: "Planet Fitness",
          date: "2024-12-17",
          amount: 10.64,
          repeating: true,
        },
      ],
    },
    {
      envelopeID: 23,
      envelopeTitle: "Streaming Services",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 46,
          envelopeID: 23,
          transactionDescription: "Netflix",
          date: "2024-12-08",
          amount: 24.45,
          repeating: true,
        },
        {
          transactionID: 47,
          envelopeID: 23,
          transactionDescription: "Youtube Premium",
          date: "2024-12-03",
          amount: 24.45,
          repeating: true,
        },
        {
          transactionID: 48,
          envelopeID: 23,
          transactionDescription: "Spotify - Kevin",
          date: "2024-12-28",
          amount: 12.75,
          repeating: true,
        },
      ],
    },
  ],
  savings: [
    {
      envelopeID: 25,
      envelopeTitle: "Home",
      envelopeDescription: "Condo insurance and home repair/improvement",
      transactions: [
        {
          transactionID: 49,
          envelopeID: 25,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 9500,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 26,
      envelopeTitle: "Cars",
      envelopeDescription:
        "Honda insurance, taxes, money for maintenance and down payments on future cars",
      transactions: [
        {
          transactionID: 50,
          envelopeID: 26,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 4176,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 27,
      envelopeTitle: "Dog",
      envelopeDescription:
        "Doggo health insurance and copays for large expenses",
      transactions: [
        {
          transactionID: 51,
          envelopeID: 27,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 2600,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 28,
      envelopeTitle: "Utilities",
      envelopeDescription:
        "Billed less than monthly (e.g. sewer tax bill) or amounts vary significantly (e.g. propane)",
      transactions: [
        {
          transactionID: 52,
          envelopeID: 28,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 1822,
          repeating: false,
        },
        {
          transactionID: 53,
          envelopeID: 28,
          transactionDescription: "Propane",
          date: "2024-12-20",
          amount: -74.38,
          repeating: true,
        },
        {
          transactionID: 54,
          envelopeID: 28,
          transactionDescription: "Willimantic Waste",
          date: "2024-12-16",
          amount: -141.27,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 29,
      envelopeTitle: "Phones",
      envelopeDescription:
        "Yearly Mint Mobile bill, savings to buy/repair phones",
      transactions: [
        {
          transactionID: 55,
          envelopeID: 29,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 574,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 30,
      envelopeTitle: "Travel",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 56,
          envelopeID: 30,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 5204,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 31,
      envelopeTitle: "Emergency",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 57,
          envelopeID: 31,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 6750,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 32,
      envelopeTitle: "Income",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 58,
          envelopeID: 32,
          transactionDescription: "Balance",
          date: "2024-12-01",
          amount: 32359.51,
          repeating: false,
        },
      ],
    },
  ],
  highestTransactionID: 59,
};
