export const budget = [
  {
    envelope: "Income",
    transactions: [
      {
        TransactionID: "1",
        AccountType: "Budget",
        EnvelopeID: "1",
        Description: "Bryant",
        Date: null,
        Amount: "4119.00",
        Repeating: null,
      },
      {
        TransactionID: "2",
        AccountType: "Budget",
        EnvelopeID: "1",
        Description: "Takeda",
        Date: null,
        Amount: "7800.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Giving",
    description: "Tithing, donations to Brazil, World Vision, Kristen",
    transactions: [
      {
        TransactionID: "3",
        AccountType: "Budget",
        EnvelopeID: "2",
        Description: "GVC",
        Date: "2024-12-01",
        Amount: "602.00",
        Repeating: null,
      },
      {
        TransactionID: "4",
        AccountType: "Budget",
        EnvelopeID: "2",
        Description: "Brazil",
        Date: "2024-12-01",
        Amount: "1300.00",
        Repeating: null,
      },
      {
        TransactionID: "5",
        AccountType: "Budget",
        EnvelopeID: "2",
        Description: "Kristen",
        Date: "2024-12-01",
        Amount: "100.00",
        Repeating: null,
      },
      {
        TransactionID: "6",
        AccountType: "Budget",
        EnvelopeID: "2",
        Description: "World Vision",
        Date: "2024-12-12",
        Amount: "45.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Savings",
    transactions: [
      {
        TransactionID: "7",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Home",
        Date: "2024-12-01",
        Amount: "500.00",
        Repeating: null,
      },
      {
        TransactionID: "8",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Cars",
        Date: "2024-12-01",
        Amount: "392.00",
        Repeating: null,
      },
      {
        TransactionID: "9",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Dog",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: null,
      },
      {
        TransactionID: "10",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Utilities",
        Date: "2024-12-01",
        Amount: "229.00",
        Repeating: null,
      },
      {
        TransactionID: "11",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Phone",
        Date: "2024-12-01",
        Amount: "58.00",
        Repeating: null,
      },
      {
        TransactionID: "12",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Travel",
        Date: "2024-12-01",
        Amount: "250.00",
        Repeating: null,
      },
      {
        TransactionID: "13",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Emergency",
        Date: "2024-12-01",
        Amount: "250.00",
        Repeating: null,
      },
      {
        TransactionID: "14",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Kevin Personal",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: null,
      },
      {
        TransactionID: "15",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Natalia Personal",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: null,
      },
      {
        TransactionID: "16",
        AccountType: "Budget",
        EnvelopeID: "3",
        Description: "Roth IRA",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Housing",
    description: "Mortgages and HOA",
    transactions: [
      {
        TransactionID: "17",
        AccountType: "Budget",
        EnvelopeID: "4",
        Description: "CT Mortgage",
        Date: "2024-12-01",
        Amount: "918.00",
        Repeating: null,
      },
      {
        TransactionID: "18",
        AccountType: "Budget",
        EnvelopeID: "4",
        Description: "MA Mortgage",
        Date: "2024-12-01",
        Amount: "2430.00",
        Repeating: null,
      },
      {
        TransactionID: "19",
        AccountType: "Budget",
        EnvelopeID: "4",
        Description: "MA HOA",
        Date: "2024-12-01",
        Amount: "528.00",
        Repeating: null,
      },
      {
        TransactionID: "20",
        AccountType: "Budget",
        EnvelopeID: "4",
        Description: "CT HOA",
        Date: "2024-12-14",
        Amount: "150.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Transportation",
    transactions: [
      {
        TransactionID: "21",
        AccountType: "Budget",
        EnvelopeID: "5",
        Description: "Tesla Lease",
        Date: "2024-12-05",
        Amount: "515.00",
        Repeating: null,
      },
      {
        TransactionID: "22",
        AccountType: "Budget",
        EnvelopeID: "5",
        Description: "Honda Loan",
        Date: "2024-12-13",
        Amount: "305.00",
        Repeating: null,
      },
      {
        TransactionID: "23",
        AccountType: "Budget",
        EnvelopeID: "5",
        Description: "Gas",
        Date: null,
        Amount: "50.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Utilities",
    transactions: [
      {
        TransactionID: "24",
        AccountType: "Budget",
        EnvelopeID: "6",
        Description: "Internet",
        Date: "2024-12-02",
        Amount: "80.00",
        Repeating: null,
      },
      {
        TransactionID: "25",
        AccountType: "Budget",
        EnvelopeID: "6",
        Description: "T-Mobile",
        Date: "2024-12-02",
        Amount: "39.00",
        Repeating: null,
      },
      {
        TransactionID: "26",
        AccountType: "Budget",
        EnvelopeID: "6",
        Description: "CT Electric",
        Date: "2024-12-05",
        Amount: "160.00",
        Repeating: null,
      },
      {
        TransactionID: "27",
        AccountType: "Budget",
        EnvelopeID: "6",
        Description: "MA Electric",
        Date: "2024-12-10",
        Amount: "132.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Groceries and Home",
    transactions: [
      {
        TransactionID: "28",
        AccountType: "Budget",
        EnvelopeID: "7",
        Description: "Grocery Stores",
        Date: null,
        Amount: "1200.00",
        Repeating: null,
      },
      {
        TransactionID: "29",
        AccountType: "Budget",
        EnvelopeID: "7",
        Description: "Amazon",
        Date: null,
        Amount: "200.00",
        Repeating: null,
      },
    ],
  },
  {
    envelope: "Health",
    transactions: [
      {
        TransactionID: "30",
        AccountType: "Budget",
        EnvelopeID: "8",
        Description: "Chiropractor",
        Date: null,
        Amount: "80.00",
        Repeating: null,
      },
      {
        TransactionID: "31",
        AccountType: "Budget",
        EnvelopeID: "8",
        Description: "Planet Fitness",
        Date: "2024-12-17",
        Amount: "11.00",
        Repeating: null,
      },
    ],
  },
];

export const checkingAccount = [
  {
    envelope: "Income",
    transactions: [
      { description: "Starting Balance", date: "2024-11-01", amount: 12100 },
      {
        TransactionID: "38",
        AccountType: "Checking",
        EnvelopeID: "1",
        Description: "Bryant",
        Date: null,
        Amount: "4119.00",
        Repeating: "1",
      },
      {
        TransactionID: "39",
        AccountType: "Checking",
        EnvelopeID: "1",
        Description: "Takeda",
        Date: null,
        Amount: "7800.00",
        Repeating: "1",
      },
    ],
  },
  {
    envelope: "Giving",
    description: "Tithing, donations to Brazil, World Vision, Kristen",
    transactions: [
      {
        TransactionID: "40",
        AccountType: "Checking",
        EnvelopeID: "2",
        Description: "GVC",
        Date: "2024-12-01",
        Amount: "602.00",
        Repeating: "1",
      },
      {
        TransactionID: "41",
        AccountType: "Checking",
        EnvelopeID: "2",
        Description: "Brazil",
        Date: "2024-12-01",
        Amount: "1300.00",
        Repeating: "1",
      },
      {
        TransactionID: "42",
        AccountType: "Checking",
        EnvelopeID: "2",
        Description: "Kristen",
        Date: "2024-12-01",
        Amount: "100.00",
        Repeating: "1",
      },
      {
        TransactionID: "43",
        AccountType: "Checking",
        EnvelopeID: "2",
        Description: "World Vision",
        Date: "2024-12-12",
        Amount: "45.00",
        Repeating: "1",
      },
    ],
  },
  {
    envelope: "Savings",
    transactions: [
      {
        TransactionID: "44",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Home",
        Date: "2024-12-01",
        Amount: "500.00",
        Repeating: "1",
      },
      {
        TransactionID: "45",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Cars",
        Date: "2024-12-01",
        Amount: "392.00",
        Repeating: "1",
      },
      {
        TransactionID: "46",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Dog",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: "1",
      },
      {
        TransactionID: "47",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Utilities",
        Date: "2024-12-01",
        Amount: "229.00",
        Repeating: "1",
      },
      {
        TransactionID: "48",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Phone",
        Date: "2024-12-01",
        Amount: "58.00",
        Repeating: "1",
      },
      {
        TransactionID: "49",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Travel",
        Date: "2024-12-01",
        Amount: "250.00",
        Repeating: "1",
      },
      {
        TransactionID: "50",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Emergency",
        Date: "2024-12-01",
        Amount: "250.00",
        Repeating: "1",
      },
      {
        TransactionID: "51",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Kevin Personal",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: "1",
      },
      {
        TransactionID: "52",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Natalia Personal",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: "1",
      },
      {
        TransactionID: "53",
        AccountType: "Checking",
        EnvelopeID: "3",
        Description: "Roth IRA",
        Date: "2024-12-01",
        Amount: "200.00",
        Repeating: "1",
      },
    ],
  },
  {
    envelope: "Housing",
    description: "Mortgages and HOA",
    transactions: [
      {
        TransactionID: "54",
        AccountType: "Checking",
        EnvelopeID: "4",
        Description: "CT Mortgage",
        Date: "2024-12-01",
        Amount: "918.00",
        Repeating: "1",
      },
      {
        TransactionID: "55",
        AccountType: "Checking",
        EnvelopeID: "4",
        Description: "MA Mortgage",
        Date: "2024-12-01",
        Amount: "2430.00",
        Repeating: "1",
      },
      {
        TransactionID: "56",
        AccountType: "Checking",
        EnvelopeID: "4",
        Description: "MA HOA",
        Date: "2024-12-01",
        Amount: "528.00",
        Repeating: "1",
      },
      {
        TransactionID: "57",
        AccountType: "Checking",
        EnvelopeID: "4",
        Description: "CT HOA",
        Date: "2024-12-14",
        Amount: "150.00",
        Repeating: "1",
      },
    ],
  },
  {
    envelope: "Transportation",
    transactions: [
      {
        TransactionID: "58",
        AccountType: "Checking",
        EnvelopeID: "5",
        Description: "Tesla Lease",
        Date: "2024-12-05",
        Amount: "515.00",
        Repeating: "1",
      },
      {
        TransactionID: "59",
        AccountType: "Checking",
        EnvelopeID: "5",
        Description: "Honda Loan",
        Date: "2024-12-13",
        Amount: "305.00",
        Repeating: "1",
      },
    ],
  },
  {
    envelope: "Utilities",
    transactions: [
      {
        TransactionID: "60",
        AccountType: "Checking",
        EnvelopeID: "6",
        Description: "Internet",
        Date: "2024-12-02",
        Amount: "80.00",
        Repeating: "1",
      },
      {
        TransactionID: "61",
        AccountType: "Checking",
        EnvelopeID: "6",
        Description: "T-Mobile",
        Date: "2024-12-02",
        Amount: "39.00",
        Repeating: "1",
      },
      {
        TransactionID: "62",
        AccountType: "Checking",
        EnvelopeID: "6",
        Description: "CT Electric",
        Date: "2024-12-05",
        Amount: "160.00",
        Repeating: "1",
      },
      {
        TransactionID: "63",
        AccountType: "Checking",
        EnvelopeID: "6",
        Description: "MA Electric",
        Date: "2024-12-10",
        Amount: "132.00",
        Repeating: "1",
      },
    ],
  },
];
