export const placeholderData = {
  budget: [
    {
      envelopeID: 1,
      envelopeTitle: "Income",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 1,
          envelopeID: 1,
          transactionDescription: "Bryant",
          date: null,
          amount: 4230,
          repeating: false,
        },
        {
          transactionID: 2,
          envelopeID: 1,
          transactionDescription: "Takeda",
          date: null,
          amount: 7800,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 2,
      envelopeTitle: "Giving",
      envelopeDescription:
        "Tithing, donations to Brazil, World Vision, Kristen",
      transactions: [
        {
          transactionID: 3,
          envelopeID: 2,
          transactionDescription: "GVC",
          date: "2024-12-01",
          amount: 602,
          repeating: false,
        },
        {
          transactionID: 4,
          envelopeID: 2,
          transactionDescription: "Brazil",
          date: "2024-12-01",
          amount: 1300,
          repeating: false,
        },
        {
          transactionID: 5,
          envelopeID: 2,
          transactionDescription: "Kristen",
          date: "2024-12-01",
          amount: 100,
          repeating: false,
        },
        {
          transactionID: 6,
          envelopeID: 2,
          transactionDescription: "World Vision",
          date: "2024-12-12",
          amount: 450,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 3,
      envelopeTitle: "Savings",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 7,
          envelopeID: 3,
          transactionDescription: "Home",
          date: "2024-12-01",
          amount: 500,
          repeating: false,
        },
        {
          transactionID: 8,
          envelopeID: 3,
          transactionDescription: "Car",
          date: "2024-12-01",
          amount: 392,
          repeating: false,
        },
        {
          transactionID: 9,
          envelopeID: 3,
          transactionDescription: "Dog",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 10,
          envelopeID: 3,
          transactionDescription: "Utilities",
          date: "2024-12-01",
          amount: 229,
          repeating: false,
        },
        {
          transactionID: 11,
          envelopeID: 3,
          transactionDescription: "Phone",
          date: "2024-12-01",
          amount: 58,
          repeating: false,
        },
        {
          transactionID: 12,
          envelopeID: 3,
          transactionDescription: "Travel",
          date: "2024-12-01",
          amount: 250,
          repeating: false,
        },
        {
          transactionID: 13,
          envelopeID: 3,
          transactionDescription: "Emergency",
          date: "2024-12-01",
          amount: 250,
          repeating: false,
        },
        {
          transactionID: 14,
          envelopeID: 3,
          transactionDescription: "Kevin Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 15,
          envelopeID: 3,
          transactionDescription: "Natalia Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 16,
          envelopeID: 3,
          transactionDescription: "Roth IRA",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 4,
      envelopeTitle: "Housing",
      envelopeDescription: "Mortgages and HOA",
      transactions: [
        {
          transactionID: 17,
          envelopeID: 4,
          transactionDescription: "CT Mortgage",
          date: "2024-12-01",
          amount: 918,
          repeating: false,
        },
        {
          transactionID: 18,
          envelopeID: 4,
          transactionDescription: "MA Mortgage",
          date: "2024-12-01",
          amount: 2430,
          repeating: false,
        },
        {
          transactionID: 19,
          envelopeID: 4,
          transactionDescription: "MA HOA",
          date: "2024-12-01",
          amount: 528,
          repeating: false,
        },
        {
          transactionID: 20,
          envelopeID: 4,
          transactionDescription: "CT HOA",
          date: "2024-12-14",
          amount: 150,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 5,
      envelopeTitle: "Transportation",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 6,
      envelopeTitle: "Utilities",
      envelopeDescription:
        "Utilities that are billed monthly and are pretty regular (electric, phone, internet)",
      transactions: [],
    },
    {
      envelopeID: 7,
      envelopeTitle: "Groceries and Home",
      envelopeDescription:
        "Include items purchased for the home from Amazon, etc.",
      transactions: [],
    },
    {
      envelopeID: 8,
      envelopeTitle: "Health",
      envelopeDescription: "Gym, doctors, chiropractor",
      transactions: [],
    },
    {
      envelopeID: 9,
      envelopeTitle: "Dog",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 10,
      envelopeTitle: "Restaurants and Entertainment",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 11,
      envelopeTitle: "Streaming Services",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 12,
      envelopeTitle: "Clothing and Personal Care",
      envelopeDescription: null,
      transactions: [],
    },
  ],
  checking: [
    {
      envelopeID: 13,
      envelopeTitle: "Income",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 21,
          envelopeID: 13,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 12100,
          repeating: true,
        },
        {
          transactionID: 22,
          envelopeID: 13,
          transactionDescription: "Bryant",
          date: "2024-12-01",
          amount: 4230,
          repeating: true,
        },
        {
          transactionID: 23,
          envelopeID: 13,
          transactionDescription: "Takeda",
          date: "2024-12-01",
          amount: 7800,
          repeating: true,
        },
      ],
    },
    {
      envelopeID: 14,
      envelopeTitle: "Giving",
      envelopeDescription:
        "Tithing, donations to Brazil, World Vision, Kristen",
      transactions: [
        {
          transactionID: 24,
          envelopeID: 14,
          transactionDescription: "GVC",
          date: "2024-12-01",
          amount: 602,
          repeating: true,
        },
        {
          transactionID: 25,
          envelopeID: 14,
          transactionDescription: "Kristen",
          date: "2024-12-01",
          amount: 100,
          repeating: true,
        },
        {
          transactionID: 26,
          envelopeID: 14,
          transactionDescription: "World Vision",
          date: "2024-12-12",
          amount: 45,
          repeating: true,
        },
      ],
    },
    {
      envelopeID: 15,
      envelopeTitle: "Savings",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 27,
          envelopeID: 15,
          transactionDescription: "Kevin Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 28,
          envelopeID: 15,
          transactionDescription: "Natalia Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
        {
          transactionID: 29,
          envelopeID: 15,
          transactionDescription: "Roth IRA",
          date: "2024-12-01",
          amount: 200,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 16,
      envelopeTitle: "Housing",
      envelopeDescription: "Mortgages and HOA",
      transactions: [
        {
          transactionID: 30,
          envelopeID: 16,
          transactionDescription: "CT Mortgage",
          date: "2024-12-01",
          amount: 918,
          repeating: false,
        },
        {
          transactionID: 31,
          envelopeID: 16,
          transactionDescription: "MA Mortgage",
          date: "2024-12-01",
          amount: 2430,
          repeating: false,
        },
        {
          transactionID: 32,
          envelopeID: 16,
          transactionDescription: "MA HOA",
          date: "2024-12-01",
          amount: 528,
          repeating: false,
        },
        {
          transactionID: 33,
          envelopeID: 16,
          transactionDescription: "CT HOA",
          date: "2024-12-14",
          amount: 150,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 17,
      envelopeTitle: "Transportation",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 18,
      envelopeTitle: "Utilities",
      envelopeDescription:
        "Utilities that are billed monthly and are pretty regular (electric, phone, internet)",
      transactions: [],
    },
    {
      envelopeID: 19,
      envelopeTitle: "Groceries and Home",
      envelopeDescription:
        "Include items purchased for the home from Amazon, etc.",
      transactions: [],
    },
    {
      envelopeID: 20,
      envelopeTitle: "Health",
      envelopeDescription: "Gym, doctors, chiropractor",
      transactions: [],
    },
    {
      envelopeID: 21,
      envelopeTitle: "Dog",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 22,
      envelopeTitle: "Restaurants and Entertainment",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 23,
      envelopeTitle: "Streaming Services",
      envelopeDescription: null,
      transactions: [],
    },
    {
      envelopeID: 24,
      envelopeTitle: "Clothing and Personal Care",
      envelopeDescription: null,
      transactions: [],
    },
  ],
  savings: [
    {
      envelopeID: 25,
      envelopeTitle: "Home",
      envelopeDescription: "Condo insurance and home repair/improvement",
      transactions: [
        {
          transactionID: 34,
          envelopeID: 25,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 9500,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 26,
      envelopeTitle: "Cars",
      envelopeDescription:
        "Honda insurance, taxes, money for maintenance and down payments on future cars",
      transactions: [
        {
          transactionID: 35,
          envelopeID: 26,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 4176,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 27,
      envelopeTitle: "Dog",
      envelopeDescription:
        "Doggo health insurance and copays for large expenses",
      transactions: [
        {
          transactionID: 36,
          envelopeID: 27,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 2600,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 28,
      envelopeTitle: "Utilities",
      envelopeDescription:
        "Billed less than monthly (e.g. sewer tax bill) or amounts vary significantly (e.g. propane)",
      transactions: [
        {
          transactionID: 37,
          envelopeID: 28,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 1822,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 29,
      envelopeTitle: "Phones",
      envelopeDescription:
        "Yearly Mint Mobile bill, savings to buy/repair phones",
      transactions: [
        {
          transactionID: 38,
          envelopeID: 29,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 574,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 30,
      envelopeTitle: "Travel",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 39,
          envelopeID: 30,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 5204,
          repeating: false,
        },
      ],
    },
    {
      envelopeID: 31,
      envelopeTitle: "Emergency",
      envelopeDescription: null,
      transactions: [
        {
          transactionID: 40,
          envelopeID: 31,
          transactionDescription: "Starting Balance",
          date: "2024-12-01",
          amount: 6750,
          repeating: false,
        },
      ],
    },
  ],
  highestTransactionID: 40,
};
