export const budget = [
  {
    envelope: "Income",
    transactions: [
      {
        transactionID: 1,
        accountType: "Budget",
        EnvelopeID: 1,
        description: "Bryant",
        date: null,
        amount: 4119,
        repeating: null,
      },
      {
        transactionID: 2,
        accountType: "Budget",
        EnvelopeID: 1,
        description: "Takeda",
        date: null,
        amount: 7800,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Giving",
    description: "Tithing, donations to Brazil, World Vision, Kristen",
    transactions: [
      {
        transactionID: 3,
        accountType: "Budget",
        EnvelopeID: 2,
        description: "GVC",
        date: "2024-12-01",
        amount: 602,
        repeating: null,
      },
      {
        transactionID: 4,
        accountType: "Budget",
        EnvelopeID: 2,
        description: "Brazil",
        date: "2024-12-01",
        amount: 1300,
        repeating: null,
      },
      {
        transactionID: 5,
        accountType: "Budget",
        EnvelopeID: 2,
        description: "Kristen",
        date: "2024-12-01",
        amount: 100,
        repeating: null,
      },
      {
        transactionID: 6,
        accountType: "Budget",
        EnvelopeID: 2,
        description: "World Vision",
        date: "2024-12-12",
        amount: 45,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Savings",
    transactions: [
      {
        transactionID: 7,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Home",
        date: "2024-12-01",
        amount: 500,
        repeating: null,
      },
      {
        transactionID: 8,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Cars",
        date: "2024-12-01",
        amount: 392,
        repeating: null,
      },
      {
        transactionID: 9,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Dog",
        date: "2024-12-01",
        amount: 200,
        repeating: null,
      },
      {
        transactionID: 10,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Utilities",
        date: "2024-12-01",
        amount: 229,
        repeating: null,
      },
      {
        transactionID: 11,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Phone",
        date: "2024-12-01",
        amount: 58,
        repeating: null,
      },
      {
        transactionID: 12,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Travel",
        date: "2024-12-01",
        amount: 250,
        repeating: null,
      },
      {
        transactionID: 13,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Emergency",
        date: "2024-12-01",
        amount: 250,
        repeating: null,
      },
      {
        transactionID: 14,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Kevin Personal",
        date: "2024-12-01",
        amount: 200,
        repeating: null,
      },
      {
        transactionID: 15,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Natalia Personal",
        date: "2024-12-01",
        amount: 200,
        repeating: null,
      },
      {
        transactionID: 16,
        accountType: "Budget",
        EnvelopeID: 3,
        description: "Roth IRA",
        date: "2024-12-01",
        amount: 200,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Housing",
    description: "Mortgages and HOA",
    transactions: [
      {
        transactionID: 17,
        accountType: "Budget",
        EnvelopeID: 4,
        description: "CT Mortgage",
        date: "2024-12-01",
        amount: 918,
        repeating: null,
      },
      {
        transactionID: 18,
        accountType: "Budget",
        EnvelopeID: 4,
        description: "MA Mortgage",
        date: "2024-12-01",
        amount: 2430,
        repeating: null,
      },
      {
        transactionID: 19,
        accountType: "Budget",
        EnvelopeID: 4,
        description: "MA HOA",
        date: "2024-12-01",
        amount: 528,
        repeating: null,
      },
      {
        transactionID: 20,
        accountType: "Budget",
        EnvelopeID: 4,
        description: "CT HOA",
        date: "2024-12-14",
        amount: 150,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Transportation",
    transactions: [
      {
        transactionID: 21,
        accountType: "Budget",
        EnvelopeID: 5,
        description: "Tesla Lease",
        date: "2024-12-05",
        amount: 515,
        repeating: null,
      },
      {
        transactionID: 22,
        accountType: "Budget",
        EnvelopeID: 5,
        description: "Honda Loan",
        date: "2024-12-13",
        amount: 305,
        repeating: null,
      },
      {
        transactionID: 23,
        accountType: "Budget",
        EnvelopeID: 5,
        description: "Gas",
        date: null,
        amount: 50,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Utilities",
    transactions: [
      {
        transactionID: 24,
        accountType: "Budget",
        EnvelopeID: 6,
        description: "Internet",
        date: "2024-12-02",
        amount: 80,
        repeating: null,
      },
      {
        transactionID: 25,
        accountType: "Budget",
        EnvelopeID: 6,
        description: "T-Mobile",
        date: "2024-12-02",
        amount: 39,
        repeating: null,
      },
      {
        transactionID: 26,
        accountType: "Budget",
        EnvelopeID: 6,
        description: "CT Electric",
        date: "2024-12-05",
        amount: 160,
        repeating: null,
      },
      {
        transactionID: 27,
        accountType: "Budget",
        EnvelopeID: 6,
        description: "MA Electric",
        date: "2024-12-10",
        amount: 132,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Groceries and Home",
    transactions: [
      {
        transactionID: 28,
        accountType: "Budget",
        EnvelopeID: 7,
        description: "Grocery Stores",
        date: null,
        amount: 1200,
        repeating: null,
      },
      {
        transactionID: 29,
        accountType: "Budget",
        EnvelopeID: 7,
        description: "Amazon",
        date: null,
        amount: 200,
        repeating: null,
      },
    ],
  },
  {
    envelope: "Health",
    transactions: [
      {
        transactionID: 30,
        accountType: "Budget",
        EnvelopeID: 8,
        description: "Chiropractor",
        date: null,
        amount: 80,
        repeating: null,
      },
      {
        transactionID: 31,
        accountType: "Budget",
        EnvelopeID: 8,
        description: "Planet Fitness",
        date: "2024-12-17",
        amount: 11,
        repeating: null,
      },
    ],
  },
];

export const checkingAccount = [
  {
    envelope: "Income",
    transactions: [
      { description: "Starting Balance", date: "2024-11-01", amount: 12100 },
      {
        transactionID: 38,
        accountType: "Checking",
        EnvelopeID: 1,
        description: "Bryant",
        date: null,
        amount: 4119,
        repeating: true,
      },
      {
        transactionID: 39,
        accountType: "Checking",
        EnvelopeID: 1,
        description: "Takeda",
        date: null,
        amount: 7800,
        repeating: true,
      },
    ],
  },
  {
    envelope: "Giving",
    description: "Tithing, donations to Brazil, World Vision, Kristen",
    transactions: [
      {
        transactionID: 40,
        accountType: "Checking",
        EnvelopeID: 2,
        description: "GVC",
        date: "2024-12-01",
        amount: 602,
        repeating: true,
      },
      {
        transactionID: 41,
        accountType: "Checking",
        EnvelopeID: 2,
        description: "Brazil",
        date: "2024-12-01",
        amount: 1300,
        repeating: true,
      },
      {
        transactionID: 42,
        accountType: "Checking",
        EnvelopeID: 2,
        description: "Kristen",
        date: "2024-12-01",
        amount: 100,
        repeating: true,
      },
      {
        transactionID: 43,
        accountType: "Checking",
        EnvelopeID: 2,
        description: "World Vision",
        date: "2024-12-12",
        amount: 45,
        repeating: true,
      },
    ],
  },
  {
    envelope: "Savings",
    transactions: [
      {
        transactionID: 44,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Home",
        date: "2024-12-01",
        amount: 500,
        repeating: true,
      },
      {
        transactionID: 45,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Cars",
        date: "2024-12-01",
        amount: 392,
        repeating: true,
      },
      {
        transactionID: 46,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Dog",
        date: "2024-12-01",
        amount: 200,
        repeating: true,
      },
      {
        transactionID: 47,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Utilities",
        date: "2024-12-01",
        amount: 229,
        repeating: true,
      },
      {
        transactionID: 48,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Phone",
        date: "2024-12-01",
        amount: 58,
        repeating: true,
      },
      {
        transactionID: 49,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Travel",
        date: "2024-12-01",
        amount: 250,
        repeating: true,
      },
      {
        transactionID: 50,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Emergency",
        date: "2024-12-01",
        amount: 250,
        repeating: true,
      },
      {
        transactionID: 51,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Kevin Personal",
        date: "2024-12-01",
        amount: 200,
        repeating: true,
      },
      {
        transactionID: 52,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Natalia Personal",
        date: "2024-12-01",
        amount: 200,
        repeating: true,
      },
      {
        transactionID: 53,
        accountType: "Checking",
        EnvelopeID: 3,
        description: "Roth IRA",
        date: "2024-12-01",
        amount: 200,
        repeating: true,
      },
    ],
  },
  {
    envelope: "Housing",
    description: "Mortgages and HOA",
    transactions: [
      {
        transactionID: 54,
        accountType: "Checking",
        EnvelopeID: 4,
        description: "CT Mortgage",
        date: "2024-12-01",
        amount: 918,
        repeating: true,
      },
      {
        transactionID: 55,
        accountType: "Checking",
        EnvelopeID: 4,
        description: "MA Mortgage",
        date: "2024-12-01",
        amount: 2430,
        repeating: true,
      },
      {
        transactionID: 56,
        accountType: "Checking",
        EnvelopeID: 4,
        description: "MA HOA",
        date: "2024-12-01",
        amount: 528,
        repeating: true,
      },
      {
        transactionID: 57,
        accountType: "Checking",
        EnvelopeID: 4,
        description: "CT HOA",
        date: "2024-12-14",
        amount: 150,
        repeating: true,
      },
    ],
  },
  {
    envelope: "Transportation",
    transactions: [
      {
        transactionID: 58,
        accountType: "Checking",
        EnvelopeID: 5,
        description: "Tesla Lease",
        date: "2024-12-05",
        amount: 515,
        repeating: true,
      },
      {
        transactionID: 59,
        accountType: "Checking",
        EnvelopeID: 5,
        description: "Honda Loan",
        date: "2024-12-13",
        amount: 305,
        repeating: true,
      },
      {
        transactionID: 64,
        accountType: "Checking",
        EnvelopeID: 5,
        description: "Shell Gas",
        date: "2024-12-13",
        amount: 42,
        repeating: false,
      },
    ],
  },
  {
    envelope: "Utilities",
    transactions: [
      {
        transactionID: 60,
        accountType: "Checking",
        EnvelopeID: 6,
        description: "Internet",
        date: "2024-12-02",
        amount: 80,
        repeating: true,
      },
      {
        transactionID: 61,
        accountType: "Checking",
        EnvelopeID: 6,
        description: "T-Mobile",
        date: "2024-12-02",
        amount: 39,
        repeating: true,
      },
      {
        transactionID: 62,
        accountType: "Checking",
        EnvelopeID: 6,
        description: "CT Electric",
        date: "2024-12-05",
        amount: 160,
        repeating: true,
      },
      {
        transactionID: 63,
        accountType: "Checking",
        EnvelopeID: 6,
        description: "MA Electric",
        date: "2024-12-10",
        amount: 132,
        repeating: true,
      },
    ],
  },
];

export const data = $state({
  budget: [
    {
      envelope: "Income",
      transactions: [
        {
          transactionID: 1,
          accountType: "Budget",
          EnvelopeID: 1,
          description: "Bryant",
          date: null,
          amount: 4119,
          repeating: null,
        },
        {
          transactionID: 2,
          accountType: "Budget",
          EnvelopeID: 1,
          description: "Takeda",
          date: null,
          amount: 7800,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Giving",
      description: "Tithing, donations to Brazil, World Vision, Kristen",
      transactions: [
        {
          transactionID: 3,
          accountType: "Budget",
          EnvelopeID: 2,
          description: "GVC",
          date: "2024-12-01",
          amount: 602,
          repeating: null,
        },
        {
          transactionID: 4,
          accountType: "Budget",
          EnvelopeID: 2,
          description: "Brazil",
          date: "2024-12-01",
          amount: 1300,
          repeating: null,
        },
        {
          transactionID: 5,
          accountType: "Budget",
          EnvelopeID: 2,
          description: "Kristen",
          date: "2024-12-01",
          amount: 100,
          repeating: null,
        },
        {
          transactionID: 6,
          accountType: "Budget",
          EnvelopeID: 2,
          description: "World Vision",
          date: "2024-12-12",
          amount: 45,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Savings",
      transactions: [
        {
          transactionID: 7,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Home",
          date: "2024-12-01",
          amount: 500,
          repeating: null,
        },
        {
          transactionID: 8,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Cars",
          date: "2024-12-01",
          amount: 392,
          repeating: null,
        },
        {
          transactionID: 9,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Dog",
          date: "2024-12-01",
          amount: 200,
          repeating: null,
        },
        {
          transactionID: 10,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Utilities",
          date: "2024-12-01",
          amount: 229,
          repeating: null,
        },
        {
          transactionID: 11,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Phone",
          date: "2024-12-01",
          amount: 58,
          repeating: null,
        },
        {
          transactionID: 12,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Travel",
          date: "2024-12-01",
          amount: 250,
          repeating: null,
        },
        {
          transactionID: 13,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Emergency",
          date: "2024-12-01",
          amount: 250,
          repeating: null,
        },
        {
          transactionID: 14,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Kevin Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: null,
        },
        {
          transactionID: 15,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Natalia Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: null,
        },
        {
          transactionID: 16,
          accountType: "Budget",
          EnvelopeID: 3,
          description: "Roth IRA",
          date: "2024-12-01",
          amount: 200,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Housing",
      description: "Mortgages and HOA",
      transactions: [
        {
          transactionID: 17,
          accountType: "Budget",
          EnvelopeID: 4,
          description: "CT Mortgage",
          date: "2024-12-01",
          amount: 918,
          repeating: null,
        },
        {
          transactionID: 18,
          accountType: "Budget",
          EnvelopeID: 4,
          description: "MA Mortgage",
          date: "2024-12-01",
          amount: 2430,
          repeating: null,
        },
        {
          transactionID: 19,
          accountType: "Budget",
          EnvelopeID: 4,
          description: "MA HOA",
          date: "2024-12-01",
          amount: 528,
          repeating: null,
        },
        {
          transactionID: 20,
          accountType: "Budget",
          EnvelopeID: 4,
          description: "CT HOA",
          date: "2024-12-14",
          amount: 150,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Transportation",
      transactions: [
        {
          transactionID: 21,
          accountType: "Budget",
          EnvelopeID: 5,
          description: "Tesla Lease",
          date: "2024-12-05",
          amount: 515,
          repeating: null,
        },
        {
          transactionID: 22,
          accountType: "Budget",
          EnvelopeID: 5,
          description: "Honda Loan",
          date: "2024-12-13",
          amount: 305,
          repeating: null,
        },
        {
          transactionID: 23,
          accountType: "Budget",
          EnvelopeID: 5,
          description: "Gas",
          date: null,
          amount: 50,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Utilities",
      transactions: [
        {
          transactionID: 24,
          accountType: "Budget",
          EnvelopeID: 6,
          description: "Internet",
          date: "2024-12-02",
          amount: 80,
          repeating: null,
        },
        {
          transactionID: 25,
          accountType: "Budget",
          EnvelopeID: 6,
          description: "T-Mobile",
          date: "2024-12-02",
          amount: 39,
          repeating: null,
        },
        {
          transactionID: 26,
          accountType: "Budget",
          EnvelopeID: 6,
          description: "CT Electric",
          date: "2024-12-05",
          amount: 160,
          repeating: null,
        },
        {
          transactionID: 27,
          accountType: "Budget",
          EnvelopeID: 6,
          description: "MA Electric",
          date: "2024-12-10",
          amount: 132,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Groceries and Home",
      transactions: [
        {
          transactionID: 28,
          accountType: "Budget",
          EnvelopeID: 7,
          description: "Grocery Stores",
          date: null,
          amount: 1200,
          repeating: null,
        },
        {
          transactionID: 29,
          accountType: "Budget",
          EnvelopeID: 7,
          description: "Amazon",
          date: null,
          amount: 200,
          repeating: null,
        },
      ],
    },
    {
      envelope: "Health",
      transactions: [
        {
          transactionID: 30,
          accountType: "Budget",
          EnvelopeID: 8,
          description: "Chiropractor",
          date: null,
          amount: 80,
          repeating: null,
        },
        {
          transactionID: 31,
          accountType: "Budget",
          EnvelopeID: 8,
          description: "Planet Fitness",
          date: "2024-12-17",
          amount: 11,
          repeating: null,
        },
      ],
    },
  ],
  checkingAccount: [
    {
      envelope: "Income",
      transactions: [
        { description: "Starting Balance", date: "2024-11-01", amount: 12100 },
        {
          transactionID: 38,
          accountType: "Checking",
          EnvelopeID: 1,
          description: "Bryant",
          date: null,
          amount: 4119,
          repeating: true,
        },
        {
          transactionID: 39,
          accountType: "Checking",
          EnvelopeID: 1,
          description: "Takeda",
          date: null,
          amount: 7800,
          repeating: true,
        },
      ],
    },
    {
      envelope: "Giving",
      description: "Tithing, donations to Brazil, World Vision, Kristen",
      transactions: [
        {
          transactionID: 40,
          accountType: "Checking",
          EnvelopeID: 2,
          description: "GVC",
          date: "2024-12-01",
          amount: 602,
          repeating: true,
        },
        {
          transactionID: 41,
          accountType: "Checking",
          EnvelopeID: 2,
          description: "Brazil",
          date: "2024-12-01",
          amount: 1300,
          repeating: true,
        },
        {
          transactionID: 42,
          accountType: "Checking",
          EnvelopeID: 2,
          description: "Kristen",
          date: "2024-12-01",
          amount: 100,
          repeating: true,
        },
        {
          transactionID: 43,
          accountType: "Checking",
          EnvelopeID: 2,
          description: "World Vision",
          date: "2024-12-12",
          amount: 45,
          repeating: true,
        },
      ],
    },
    {
      envelope: "Savings",
      transactions: [
        {
          transactionID: 44,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Home",
          date: "2024-12-01",
          amount: 500,
          repeating: true,
        },
        {
          transactionID: 45,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Cars",
          date: "2024-12-01",
          amount: 392,
          repeating: true,
        },
        {
          transactionID: 46,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Dog",
          date: "2024-12-01",
          amount: 200,
          repeating: true,
        },
        {
          transactionID: 47,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Utilities",
          date: "2024-12-01",
          amount: 229,
          repeating: true,
        },
        {
          transactionID: 48,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Phone",
          date: "2024-12-01",
          amount: 58,
          repeating: true,
        },
        {
          transactionID: 49,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Travel",
          date: "2024-12-01",
          amount: 250,
          repeating: true,
        },
        {
          transactionID: 50,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Emergency",
          date: "2024-12-01",
          amount: 250,
          repeating: true,
        },
        {
          transactionID: 51,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Kevin Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: true,
        },
        {
          transactionID: 52,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Natalia Personal",
          date: "2024-12-01",
          amount: 200,
          repeating: true,
        },
        {
          transactionID: 53,
          accountType: "Checking",
          EnvelopeID: 3,
          description: "Roth IRA",
          date: "2024-12-01",
          amount: 200,
          repeating: true,
        },
      ],
    },
    {
      envelope: "Housing",
      description: "Mortgages and HOA",
      transactions: [
        {
          transactionID: 54,
          accountType: "Checking",
          EnvelopeID: 4,
          description: "CT Mortgage",
          date: "2024-12-01",
          amount: 918,
          repeating: true,
        },
        {
          transactionID: 55,
          accountType: "Checking",
          EnvelopeID: 4,
          description: "MA Mortgage",
          date: "2024-12-01",
          amount: 2430,
          repeating: true,
        },
        {
          transactionID: 56,
          accountType: "Checking",
          EnvelopeID: 4,
          description: "MA HOA",
          date: "2024-12-01",
          amount: 528,
          repeating: true,
        },
        {
          transactionID: 57,
          accountType: "Checking",
          EnvelopeID: 4,
          description: "CT HOA",
          date: "2024-12-14",
          amount: 150,
          repeating: true,
        },
      ],
    },
    {
      envelope: "Transportation",
      transactions: [
        {
          transactionID: 58,
          accountType: "Checking",
          EnvelopeID: 5,
          description: "Tesla Lease",
          date: "2024-12-05",
          amount: 515,
          repeating: true,
        },
        {
          transactionID: 59,
          accountType: "Checking",
          EnvelopeID: 5,
          description: "Honda Loan",
          date: "2024-12-13",
          amount: 305,
          repeating: true,
        },
        {
          transactionID: 64,
          accountType: "Checking",
          EnvelopeID: 5,
          description: "Shell Gas",
          date: "2024-12-13",
          amount: 42,
          repeating: false,
        },
      ],
    },
    {
      envelope: "Utilities",
      transactions: [
        {
          transactionID: 60,
          accountType: "Checking",
          EnvelopeID: 6,
          description: "Internet",
          date: "2024-12-02",
          amount: 80,
          repeating: true,
        },
        {
          transactionID: 61,
          accountType: "Checking",
          EnvelopeID: 6,
          description: "T-Mobile",
          date: "2024-12-02",
          amount: 39,
          repeating: true,
        },
        {
          transactionID: 62,
          accountType: "Checking",
          EnvelopeID: 6,
          description: "CT Electric",
          date: "2024-12-05",
          amount: 160,
          repeating: true,
        },
        {
          transactionID: 63,
          accountType: "Checking",
          EnvelopeID: 6,
          description: "MA Electric",
          date: "2024-12-10",
          amount: 132,
          repeating: true,
        },
      ],
    },
  ],
});
